/*
    app.js
    code for our demo application
 */

"use strict";

//this is the base URL for all task objects managed by your application
//requesting this with a GET will get all tasks objects
//sending a POST to this will insert a new task object
//sending a PUT to this URL + '/' + task.objectId will update an existing task
//sending a DELETE to this URL + '/' + task.objectId will delete an existing task
var tasksUrl = 'https://api.parse.com/1/classes/tasks';

// what goes in the array is an array of other angular modules
angular.module('ToDoApp', ['ui.bootstrap'])
    .config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = '3FR9LArrSkDlsjjeoXuvwjrQ4K0DVUuNufkskKpq';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'iMgJTiZJJ8B6OIJuDBYQNEbVs3fap5bA9gcPEDdj';
    })
    .controller('TasksController', function($scope, $http) {
        // in-line anonymous function
        $scope.refreshTasks = function() {
            $scope.loading = true;
            // add a query string
            // adds a where clause like from SQL, want data only when the 'done' box is not checked
            $http.get(tasksUrl + '?where={"done":false}')
                //resulting object call success handler
                .success(function(data) {
                    $scope.tasks = data.results;
                })
                .error(function(err) {
                    $scope.errorMessage = err;
                })
                .finally(function () {
                  $scope.loading = false;
                });
        };

        $scope.refreshTasks();

        $scope.newTask = {done: false};

        $scope.addTask = function() {
            // need to send new task to parse to save it in a database using .post()

            $http.post(tasksUrl, $scope.newTask)
                .success(function(responseData) {
                    $scope.newTask.objectId = responseData.objectId;
                    $scope.tasks.push($scope.newTask);
                    $scope.newTask = {done: false};
                })
                .error(function(err) {
                    $scope.errorMessage = err;
                });
        };
        //need to send the update up to parse using .put()
        $scope.updateTask = function(task) {
            $http.put(tasksUrl + '/' + task.objectId, task)
                .success(function(responseData) {
                    // don't need to do anything here
                    //we might want to show feedback that update was successful

                })
                .error(function(err) {
                    $scope.errorMessage = err
                })
                .finally(function() {
                   $scope.updating = false;
                });
        };

        $scope.incrementVotes = function(task, amount) {
            var postData = {
              votes: {
                  __op: "Increment",
                  amount: amount
              }
            };
            $http.put(tasksUrl + '/' + task.objectId, postData)
                .success(function(respData) {
                    task.votes = respData.votes;
                 })
                .error(function(err) {
                    console.log(err);
                })
                .finally (function() {
                    $scope.updating = false;
                });
        }

    });
